### ISSUE TITLE
Get colors from unsupported wallpaper plugins by taking a screenshot of the desktop view

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/kde-material-you-colors#163]
**Is your feature request related to a problem? Please describe.**
Currently, the current wallpaper information is obtained using [Plasma Scripting API](https://develop.kde.org/docs/plasma/scripting/), but only works if the wallpaper plugin itself stores the value of the current wallpaper (like an image path or color)

**Describe the solution you'd like**
Find a way to grab a screenshot of the desktop view

* [x] Should work completely in the background
* [x] Should work without user intervention
* [x] Should capture the desktop only (not panels)
* [ ] #165

**Todo**

* [x] Finding the desktop window: 
	* Using the [KWin Scripting API](https://develop.kde.org/docs/plasma/kwin/) directly (preferred)
* [x] Taking screenshot of the desktop window
	* With dbus using [org.kde.KWin /org/kde/KWin/ScreenShot2 org.kde.KWin.ScreenShot2.CaptureWindow](https://github.com/KDE/kwin/tree/master/src/plugins/screenshot)
* [x] Implement as fallback when wallpaper plugin fails

**Additional context**
[BUG:449986 - Spectacle: New capture mode: Window by properties](https://bugs.kde.org/show_bug.cgi?id=449986)

**Comment by luisbocanegra** [comment]
So there is this KWin plugin https://github.com/KDE/kwin/tree/master/src/plugins/screenshot which is used to take screenshots by Spectacle. After reading https://github.com/KDE/kwin/blob/master/src/plugins/screenshot/org.kde.KWin.ScreenShot2.xml and a bit of trial and error 😆 managed to get a POC scrip working 🎉

![Screenshot_20231202_125941](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/5da21fae-4032-4a55-9efe-4dfaf6a51815)

**Comment by luisbocanegra** [comment]
Testing is needed to ensure this works as expected for the new release:

First clone and run the main branch
```
git clone https://github.com/luisbocanegra/kde-material-you-colors
export PYTHONPATH=/home/luis/projects/kde-material-you-colors/src:$PYTHONPATH
python -m kde_material_you_colors.main
```
Try setting different wallpaper plugins that are not supported in previous releases like "Hunyango" and it should pick the colors from it.

To control how often screenshots are taken please refer to the end of the sample configuration file https://github.com/luisbocanegra/kde-material-you-colors/blob/main/src/kde_material_you_colors/data/sample_config.conf
